apiVersion: ray.io/v1
kind: RayService
metadata:
  name: rayservice-sample
spec:
  serveConfigV2: |
    applications:
      - name: hello_world
        import_path: test.deployment_graph
        route_prefix: /greet
        runtime_env:
          working_dir: "https://github.com/Yicheng-Lu-llll/serve-file/archive/refs/tags/sleep-duration-hello-word.zip"
        deployments:
          - name: helloWorld
            num_replicas: 2
            ray_actor_options:
              num_cpus: 1

  rayClusterConfig:
    rayVersion: '2.8.0' # should match the Ray version in the image of the containers
    headGroupSpec:
      rayStartParams:
        dashboard-host: '0.0.0.0'
      template:
        spec:
          containers:
            - name: ray-head
              image: rayproject/ray:2.8.0
              env:
                - name: RAY_SERVE_PROXY_MIN_DRAINING_PERIOD_S
                  value: "600"
              resources:
                limits:
                  cpu: 1
                  memory: 2Gi
                requests:
                  cpu: 1
                  memory: 2Gi
              ports:
                - containerPort: 6379
                  name: gcs-server
                - containerPort: 8265 # Ray dashboard
                  name: dashboard
                - containerPort: 10001
                  name: client
                - containerPort: 8000
                  name: serve
    workerGroupSpecs:
      - replicas: 1
        minReplicas: 1
        maxReplicas: 5
        groupName: small-group
        rayStartParams: {}
        template:
          spec:
            containers:
              - name: ray-worker # must consist of lower case alphanumeric characters or '-', and must start and end with an alphanumeric character (e.g. 'my-name',  or '123-abc'
                image: rayproject/ray:2.8.0
                env:
                  - name: RAY_SERVE_PROXY_MIN_DRAINING_PERIOD_S
                    value: "600"
                lifecycle:
                  preStop:
                    exec:
                      command: ["/bin/sh","-c","ray stop"]
                resources:
                  limits:
                    cpu: "1"
                    memory: "2Gi"
                  requests:
                    cpu: "1"
                    memory: "2Gi"
